# Generated by Django 5.2.6 on 2025-09-23 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('JRS', 'Jersey'), ('BOT', 'Football Boots'), ('BAL', 'Football Ball'), ('ACC', 'Accessories'), ('EQP', 'Training Equipment')], default='JRS', max_length=3),
        ),
    ]
