# Generated by Django 5.2.6 on 2025-10-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='second_image',
            field=models.URLField(blank=True, help_text='Optional second image for hover effect', null=True),
        ),
    ]
